---

- hosts: "{{ hosts | default('jumpbox') }}"
  vars:
    redis_exporter_version: 1.3.5
  tasks:
    - name: test connection
      ping:

    - name: create group Node exporter
      become: yes
      group:
        name: node_exporter
        state: present

    - name: create user Node exporter
      user:
        name: node_exporter
        group: node_exporter
        createhome: no
        system: yes
        state: present
      become: yes

    - name: create opt directory for redis
      file:
        path: /opt/redis
        state: directory
      become: yes

    - name: download redis exporter
      get_url:
        url: https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/redis
      become: yes

    - name: unarchive redis exporter
      unarchive:
        remote_src: yes
        src: /opt/redis/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/redis
      become: yes

    - name: Move file redis exporter
      command: mv /opt/redis/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter /usr/local/bin/
      become: yes

    - name: install unit file to systemd
      template:
        src: redis_exporter.j2
        dest: /etc/systemd/system/redis_exporter.service
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: redis_exporter.service
      become: yes

    - name: Remove redis exporter zip
      file:
        path: /opt/redis/redis_exporter-{{ redis_exporter_version }}.linux-amd64.tar.gz
        state: absent
      become: yes

    - name: Remove redis exporter folder
      file:
        path: /opt/redis/redis_exporter-{{ redis_exporter_version }}.linux-amd64
        state: absent
      become: yes